local M = {}

M.setup = function(colors, utils)
    local c  = colors.palette
    local hl = utils.highlight_all

    hl({
        -- GitSigns
        GitSignsAdd                         = { fg = c.green,      bg = c.bg0                      },
        GitSignsChange                      = { fg = c.blue,       bg = c.bg0                      },
        GitSignsDelete                      = { fg = c.red,        bg = c.bg0                      },
        GitSignsAddNr                       = { fg = c.green                                       },
        GitSignsChangeNr                    = { fg = c.blue                                        },
        GitSignsDeleteNr                    = { fg = c.red                                         },
        GitSignsAddLn                       = { bg = c.bg_dark                                     },
        GitSignsChangeLn                    = { bg = c.bg_dark                                     },
        GitSignsDeleteLn                    = { bg = c.bg_dark                                     },

        -- Telescope
        TelescopeBorder                     = { fg = c.border,     bg = c.bg_float                 },
        TelescopeNormal                     = { fg = c.fg0,        bg = c.bg_float                 },
        TelescopeSelection                  = { fg = c.fg0,        bg = c.bg3,      bold = true    },
        TelescopeSelectionCaret             = { fg = c.cyan                                        },
        TelescopeMultiSelection             = { fg = c.purple                                      },
        TelescopeMultiIcon                  = { fg = c.cyan                                        },
        TelescopeMatching                   = { fg = c.yellow,     bold = true                     },
        TelescopePromptPrefix               = { fg = c.blue                                        },
        TelescopePromptNormal               = { fg = c.fg0,        bg = c.bg_float                 },
        TelescopePromptBorder               = { fg = c.border,     bg = c.bg_float                 },
        TelescopePromptTitle                = { fg = c.magenta,    bold = true                     },
        TelescopePreviewTitle               = { fg = c.green,      bold = true                     },
        TelescopeResultsTitle               = { fg = c.cyan,       bold = true                     },
        TelescopePromptCounter              = { fg = c.fg2                                         },

        -- Completion (nvim-cmp)
        CmpItemAbbrDeprecated               = { fg = c.fg3,        strikethrough = true            },
        CmpItemAbbrMatch                    = { fg = c.yellow,     bold = true                     },
        CmpItemAbbrMatchFuzzy               = { fg = c.yellow                                      },
        CmpItemKindDefault                  = { fg = c.fg2                                         },
        CmpItemMenu                         = { fg = c.fg2                                         },
        CmpItemKindKeyword                  = { fg = c.purple                                      },
        CmpItemKindVariable                 = { fg = c.cyan                                        },
        CmpItemKindConstant                 = { fg = c.orange                                      },
        CmpItemKindReference                = { fg = c.cyan                                        },
        CmpItemKindValue                    = { fg = c.orange                                      },
        CmpItemKindFunction                 = { fg = c.magenta                                     },
        CmpItemKindMethod                   = { fg = c.magenta                                     },
        CmpItemKindConstructor              = { fg = c.blue                                        },
        CmpItemKindClass                    = { fg = c.purple                                      },
        CmpItemKindInterface                = { fg = c.purple                                      },
        CmpItemKindStruct                   = { fg = c.purple                                      },
        CmpItemKindEvent                    = { fg = c.yellow                                      },
        CmpItemKindEnum                     = { fg = c.purple                                      },
        CmpItemKindUnit                     = { fg = c.orange                                      },
        CmpItemKindModule                   = { fg = c.blue                                        },
        CmpItemKindProperty                 = { fg = c.cyan                                        },
        CmpItemKindField                    = { fg = c.cyan                                        },
        CmpItemKindTypeParameter            = { fg = c.purple                                      },
        CmpItemKindEnumMember               = { fg = c.orange                                      },
        CmpItemKindOperator                 = { fg = c.teal                                        },
        CmpItemKindSnippet                  = { fg = c.green                                       },
        CmpItemKindText                     = { fg = c.fg1                                         },
        CmpItemKindFile                     = { fg = c.blue                                        },
        CmpItemKindFolder                   = { fg = c.blue                                        },

        -- WhichKey
        WhichKey                            = { fg = c.cyan,       bold = true                     },
        WhichKeyGroup                       = { fg = c.purple                                      },
        WhichKeyDesc                        = { fg = c.fg1                                         },
        WhichKeySeperator                   = { fg = c.fg2                                         },
        WhichKeyFloat                       = { bg = c.bg_float                                    },
        WhichKeyValue                       = { fg = c.green                                       },

        -- NvimTree
        NvimTreeNormal                      = { fg = c.fg1,        bg = c.bg_dark                  },
        NvimTreeRootFolder                  = { fg = c.purple,     bold = true                     },
        NvimTreeGitDirty                    = { fg = c.yellow                                      },
        NvimTreeGitNew                      = { fg = c.green                                       },
        NvimTreeGitDeleted                  = { fg = c.red                                         },
        NvimTreeSpecialFile                 = { fg = c.yellow,     underline = true                },
        NvimTreeIndentMarker                = { fg = c.fg3                                         },
        NvimTreeImageFile                   = { fg = c.purple                                      },
        NvimTreeSymlink                     = { fg = c.cyan                                        },
        NvimTreeFolderName                  = { fg = c.blue                                        },
        NvimTreeFolderIcon                  = { fg = c.blue                                        },
        NvimTreeOpenedFolderName            = { fg = c.blue,       bold = true                     },

        -- Indent Blankline
        IblIndent                           = { fg = c.bg2                                         },
        IblScope                            = { fg = c.purple                                      },

        -- Dashboard
        DashboardShortCut                   = { fg = c.cyan                                        },
        DashboardHeader                     = { fg = c.purple                                      },
        DashboardCenter                     = { fg = c.blue                                        },
        DashboardFooter                     = { fg = c.yellow,     italic = true                  },

        -- Lazy.nvim
        LazyProgressTodo                    = { fg = c.fg3                                         },
        LazyProgressDone                    = { fg = c.green                                       },
        LazyCommit                          = { fg = c.yellow                                      },
        LazyCommitType                      = { fg = c.purple                                      },
        LazyReasonStart                     = { fg = c.blue                                        },
        LazyReasonPlugin                    = { fg = c.cyan                                        },
        LazyReasonEvent                     = { fg = c.orange                                      },
        LazyReasonKeys                      = { fg = c.green                                       },
        LazyReasonImport                    = { fg = c.magenta                                     },
        LazyReasonSource                    = { fg = c.red                                         },
        LazyReasonRuntime                   = { fg = c.purple                                      },
        LazyReasonCmd                       = { fg = c.yellow                                      },
        LazyReasonFt                        = { fg = c.cyan                                        },
        LazyOperationNot                    = { fg = c.red                                         },

        -- Flash.nvim
        FlashBackdrop                       = { fg = c.fg3                                         },
        FlashMatch                          = { fg = c.bg0,       bg = c.cyan,     bold = true    },
        FlashCurrent                        = { fg = c.bg0,       bg = c.orange,   bold = true    },
        FlashLabel                          = { fg = c.bg0,       bg = c.magenta,  bold = true    },
        FlashPrompt                         = { fg = c.cyan                                        },
        FlashPromptIcon                     = { fg = c.cyan                                        },
        FlashCursor                         = { reverse = true                                     },

        -- Mason
        MasonHeader                         = { fg = c.bg0,       bg = c.cyan,     bold = true    },
        MasonHeaderSecondary                = { fg = c.bg0,       bg = c.purple,   bold = true    },
        MasonHighlight                      = { fg = c.cyan                                        },
        MasonHighlightBlock                 = { fg = c.bg0,       bg = c.cyan                     },
        MasonHighlightBlockBold             = { fg = c.bg0,       bg = c.cyan,     bold = true    },
        MasonMuted                          = { fg = c.fg3                                         },
        MasonMutedBlock                     = { fg = c.fg3,       bg = c.bg1                      },
        MasonMutedBlockBold                 = { fg = c.fg3,       bg = c.bg1,      bold = true    },

        -- Noice
        NoiceCompletionItemKindDefault      = { fg = c.fg3                                         },
        NoiceCompletionItemMenu             = { fg = c.fg3                                         },
        NoiceCmdlineIcon                    = { fg = c.cyan                                        },
        NoiceCmdlineIconInput               = { fg = c.yellow                                      },
        NoiceCmdlineIconLua                 = { fg = c.blue                                        },
        NoiceCmdlinePopup                   = { fg = c.fg0,       bg = c.bg_float                 },
        NoiceCmdlinePopupBorder             = { fg = c.border,    bg = c.bg_float                 },
        NoiceCmdlinePopupTitle              = { fg = c.purple,    bold = true                     },
        NoiceConfirm                        = { fg = c.fg0,       bg = c.bg_float                 },
        NoiceConfirmBorder                  = { fg = c.border,    bg = c.bg_float                 },

        -- Mini.nvim
        MiniCursorword                      = { bg = c.bg2                                         },
        MiniCursorwordCurrent               = { bg = c.bg2                                         },
        MiniIndentscopeSymbol               = { fg = c.purple                                      },
        MiniJump                            = { fg = c.bg0,       bg = c.cyan,     bold = true    },
        MiniJump2dSpot                      = { fg = c.bg0,       bg = c.cyan,     bold = true    },
        MiniStarterCurrent                  = { fg = c.cyan                                        },
        MiniStarterFooter                   = { fg = c.yellow,    italic = true                   },
        MiniStarterHeader                   = { fg = c.purple                                      },
        MiniStarterInactive                 = { fg = c.fg3                                         },
        MiniStarterItem                     = { fg = c.fg1                                         },
        MiniStarterItemBullet               = { fg = c.cyan                                        },
        MiniStarterItemPrefix               = { fg = c.yellow                                      },
        MiniStarterSection                  = { fg = c.blue                                        },
        MiniStarterQuery                    = { fg = c.green                                       },
        MiniStatuslineDevinfo               = { fg = c.fg2,       bg = c.bg2                      },
        MiniStatuslineFileinfo              = { fg = c.fg2,       bg = c.bg2                      },
        MiniStatuslineFilename              = { fg = c.fg1,       bg = c.bg1                      },
        MiniStatuslineInactive              = { fg = c.fg3,       bg = c.bg1                      },
        MiniStatuslineModeCommand           = { fg = c.bg0,       bg = c.yellow,   bold = true    },
        MiniStatuslineModeInsert            = { fg = c.bg0,       bg = c.green,    bold = true    },
        MiniStatuslineModeNormal            = { fg = c.bg0,       bg = c.blue,     bold = true    },
        MiniStatuslineModeOther             = { fg = c.bg0,       bg = c.cyan,     bold = true    },
        MiniStatuslineModeReplace           = { fg = c.bg0,       bg = c.red,      bold = true    },
        MiniStatuslineModeVisual            = { fg = c.bg0,       bg = c.purple,   bold = true    },
        MiniSurround                        = { fg = c.bg0,       bg = c.orange                   },
        MiniTablineCurrent                  = { fg = c.fg0,       bg = c.bg2,      bold = true    },
        MiniTablineFill                     = { bg = c.bg1                                         },
        MiniTablineHidden                   = { fg = c.fg2,       bg = c.bg1                      },
        MiniTablineModifiedCurrent          = { fg = c.orange,    bg = c.bg2                      },
        MiniTablineModifiedHidden           = { fg = c.orange,    bg = c.bg1                      },
        MiniTablineModifiedVisible          = { fg = c.orange,    bg = c.bg1                      },
        MiniTablineTabpagesection           = { fg = c.bg0,       bg = c.purple,   bold = true    },
        MiniTablineVisible                  = { fg = c.fg1,       bg = c.bg1                      },
        MiniTestEmphasis                    = { bold = true                                        },
        MiniTestFail                        = { fg = c.red,       bold = true                     },
        MiniTestPass                        = { fg = c.green,     bold = true                     },
        MiniTrailspace                      = { bg = c.red                                         },

        -- Leap.nvim
        LeapMatch                           = { fg = c.bg1,       bg = c.cyan,     bold = true    },
        LeapLabelPrimary                    = { fg = c.bg1,       bg = c.magenta,  bold = true    },
        LeapLabelSecondary                  = { fg = c.bg0,       bg = c.blue,     bold = true    },
        LeapBackdrop                        = { fg = c.fg3                                         },

        -- Notify
        NotifyERRORBorder                   = { fg = c.red                                         },
        NotifyWARNBorder                    = { fg = c.orange                                      },
        NotifyINFOBorder                    = { fg = c.blue                                        },
        NotifyDEBUGBorder                   = { fg = c.fg3                                         },
        NotifyTRACEBorder                   = { fg = c.purple                                      },
        NotifyERRORIcon                     = { fg = c.red                                         },
        NotifyWARNIcon                      = { fg = c.orange                                      },
        NotifyINFOIcon                      = { fg = c.blue                                        },
        NotifyDEBUGIcon                     = { fg = c.fg3                                         },
        NotifyTRACEIcon                     = { fg = c.purple                                      },
        NotifyERRORTitle                    = { fg = c.red                                         },
        NotifyWARNTitle                     = { fg = c.orange                                      },
        NotifyINFOTitle                     = { fg = c.blue                                        },
        NotifyDEBUGTitle                    = { fg = c.fg3                                         },
        NotifyTRACETitle                    = { fg = c.purple                                      },
    })
end

return M
